spring.application.name=Consultorio-Dental-S-Back

#CONFIGURATION DATABASE LOCAL
spring.datasource.url=jdbc:mysql://localhost:3307/db_dentals_web_system
spring.datasource.username=root
spring.datasource.password=260419
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#CONFIGURATION JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
